from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QGroupBox,QApplication, QWidget,QPushButton,QHBoxLayout,QVBoxLayout,QLabel,QMessageBox,QRadioButton
app=QApplication([])

main_win=QWidget()
main_win.setWindowTitle('Memory card')

question =QLabel('Какой национальности не существует?')
btn_OK = QPushButton('Ответить')
RadioGroupBox=QGroupBox('Варианты ответов')
btn_answer1=QRadioButton('Энцы')
btn_answer2=QRadioButton('Смурфы')
btn_answer3=QRadioButton('Чулымцы')
btn_answer4=QRadioButton('Алеуты')
layoutq=QHBoxLayout()
layout1=QHBoxLayout()
layout2=QVBoxLayout()
layout3=QVBoxLayout()
#layout1.addWidget(question,alignment=Qt.AlignCenter)
layout2.addWidget(btn_answer1)
layout2.addWidget(btn_answer2)
layout3.addWidget(btn_answer3)
layout3.addWidget(btn_answer4)
layout_main=QVBoxLayout()
layout1.addLayout(layout2)
layout1.addLayout(layout3)
#layout_main.addLayout(layout3)
RadioGroupBox.setLayout(layout1)
layout_line1 = QHBoxLayout() 
layout_line2 = QHBoxLayout() 
layout_line3 = QHBoxLayout() 
layout_line1.addWidget(question, alignment=(Qt.AlignHCenter | Qt.AlignVCenter))
layout_line2.addWidget(RadioGroupBox)
layout_card = QVBoxLayout()
main_win.show()
app.exec_()